### ISSUE TITLE
add test coverage for `serial/fmt/json`

### ISSUE THREAD

**Issue by jchlapinski** [kodegenix/kg-tree#7]
1. Add tests for all error kinds
1. Add tests for correct input
1. Attach our json parsing to the `NodeRef::from_json()` method (instead of serde)
1. Add tests for `NodeRef::from_json()` method
1. Remove all warnings

**Comment by maksymilianciak** [comment]
https://github.com/kodegenix/kg-tree/tree/json-parsing-tests

**Comment by maksymilianciak** [comment]
https://github.com/kodegenix/kg-tree/pull/9
